"""update

Revision ID: c0b110d7991d
Revises: 
Create Date: 2021-02-10 22:03:47.591281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b110d7991d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pruebainsert')
    op.drop_table('spatial_ref_sys')
    op.drop_index('ferrocarril_wkb_geometry_geom_idx', table_name='ferrocarril')
    op.drop_table('ferrocarril')
    op.drop_index('estaciones_dgt_wkb_geometry_geom_idx', table_name='estaciones_dgt')
    op.drop_table('estaciones_dgt')
    op.drop_index('estrada_l_25_wkb_geometry_geom_idx', table_name='estrada_l_25')
    op.drop_column('estrada_l_25', 'denominaci')
    op.drop_column('estrada_l_25', 'estado')
    op.drop_column('estrada_l_25', 'num_enlace')
    op.drop_column('estrada_l_25', 'objectid')
    op.drop_column('estrada_l_25', 'data_estad')
    op.drop_column('estrada_l_25', 'transferid')
    op.drop_column('estrada_l_25', 'peaxe')
    op.drop_column('estrada_l_25', 'shape_leng')
    op.drop_column('estrada_l_25', 'observacio')
    op.drop_column('estrada_l_25', 'wkb_geometry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estrada_l_25', sa.Column('wkb_geometry', sa.NullType(), autoincrement=False, nullable=True))
    op.add_column('estrada_l_25', sa.Column('observacio', sa.VARCHAR(length=254), autoincrement=False, nullable=True))
    op.add_column('estrada_l_25', sa.Column('shape_leng', sa.NUMERIC(precision=19, scale=11), autoincrement=False, nullable=True))
    op.add_column('estrada_l_25', sa.Column('peaxe', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('estrada_l_25', sa.Column('transferid', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('estrada_l_25', sa.Column('data_estad', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('estrada_l_25', sa.Column('objectid', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=True))
    op.add_column('estrada_l_25', sa.Column('num_enlace', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('estrada_l_25', sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('estrada_l_25', sa.Column('denominaci', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index('estrada_l_25_wkb_geometry_geom_idx', 'estrada_l_25', ['wkb_geometry'], unique=False)
    op.create_table('estaciones_dgt',
    sa.Column('ogc_fid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wkb_geometry', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('objectid', sa.NUMERIC(precision=5, scale=0), autoincrement=False, nullable=True),
    sa.Column('id_vial', sa.NUMERIC(precision=12, scale=0), autoincrement=False, nullable=True),
    sa.Column('id_tramo', sa.NUMERIC(precision=12, scale=0), autoincrement=False, nullable=True),
    sa.Column('id_porpk', sa.NUMERIC(precision=12, scale=0), autoincrement=False, nullable=True),
    sa.Column('numero', sa.NUMERIC(precision=3, scale=0), autoincrement=False, nullable=True),
    sa.Column('sentidopk', sa.NUMERIC(precision=1, scale=0), autoincrement=False, nullable=True),
    sa.Column('sentidopkd', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('fuente', sa.NUMERIC(precision=2, scale=0), autoincrement=False, nullable=True),
    sa.Column('fuented', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('descripcio', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('nombre_car', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('fecha_alta', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('layer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ogc_fid', name='estaciones_dgt_pk')
    )
    op.create_index('estaciones_dgt_wkb_geometry_geom_idx', 'estaciones_dgt', ['wkb_geometry'], unique=False)
    op.create_table('ferrocarril',
    sa.Column('ogc_fid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wkb_geometry', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('objectid', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.Column('layer', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('tramo_nome', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('doble_via', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('electrific', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('situacion', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('data_inaug', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('shape_leng', sa.NUMERIC(precision=19, scale=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ogc_fid', name='ferrocarril_pk')
    )
    op.create_index('ferrocarril_wkb_geometry_geom_idx', 'ferrocarril', ['wkb_geometry'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.create_table('pruebainsert',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('n1', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('n2', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('n3', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
